// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateCart(ctx context.Context, arg CreateCartParams) (*Cart, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (*Category, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (*Order, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (*Product, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeleteCart(ctx context.Context, cartID int32) error
	DeleteCategory(ctx context.Context, categoryID int32) error
	DeleteOrder(ctx context.Context, orderID int16) error
	DeleteProduct(ctx context.Context, productID int16) error
	DeleteToken(ctx context.Context, userToken *string) error
	FindAllCategory(ctx context.Context) ([]*Category, error)
	FindAllOrder(ctx context.Context) ([]*Order, error)
	FindAllProduct(ctx context.Context) ([]*Product, error)
	FindAllProductPaging(ctx context.Context, arg FindAllProductPagingParams) ([]*Product, error)
	FindCartByCustomerAndProduct(ctx context.Context, arg FindCartByCustomerAndProductParams) (*FindCartByCustomerAndProductRow, error)
	FindCartByCustomerId(ctx context.Context, customerID string) ([]*FindCartByCustomerIdRow, error)
	FindCartByCustomerPaging(ctx context.Context, arg FindCartByCustomerPagingParams) ([]*FindCartByCustomerPagingRow, error)
	FindCategoryById(ctx context.Context, categoryID int32) (*Category, error)
	FindOrderById(ctx context.Context, orderID int16) (*Order, error)
	FindProductById(ctx context.Context, productID int16) (*Product, error)
	FindUserByPhone(ctx context.Context, userPhone *string) (*FindUserByPhoneRow, error)
	FindUserByUserPassword(ctx context.Context, arg FindUserByUserPasswordParams) (*FindUserByUserPasswordRow, error)
	FindUserByUsername(ctx context.Context, userName *string) (*FindUserByUsernameRow, error)
	GetUserRoles(ctx context.Context, arg GetUserRolesParams) ([]*GetUserRolesRow, error)
	UpdateCartQty(ctx context.Context, arg UpdateCartQtyParams) (*Cart, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (*Category, error)
	UpdateOrderShip(ctx context.Context, arg UpdateOrderShipParams) (*Order, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (*Product, error)
	UpdateToken(ctx context.Context, arg UpdateTokenParams) (*User, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (*User, error)
	UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
